### ISSUE TITLE
Cambiamento della data di consegna del progetto

### ISSUE THREAD

**Issue by alorenzi10** [alorenzi10/Monopoly#2]
Buongiorno,
A causa di difficoltà con altre materie d'esame e impegni personali, come team non riusciremmo a concludere il progetto in modo soddisfacente. 
Purtroppo le difficoltà riscontrate negli altri esami hanno richiesto un maggiore impegno e tempo di studio, che ha avuto un impatto sulle nostre capacità di concentrarci sul presente progetto. 
Per questo vorremmo consegnare il progetto completato per la sessione di Aprile.
Se cioè è possibile modificheremo il project plan in base alle nuove tempistiche e richiederemo una nuova approvazione.
Grazie in anticipo e cordiali saluti.

**Comment by garganti** [comment]
Ok va bene, potete presentare il progetto con l'appello di febbraio.
